Including validations to job property paths.
Leaf-Agriculture/billing-data-aggregation-job pull request #6
Opened 2022-08-18 15:59 UTC by DouglasVinicius

2022-08-18 16:00 UTC, DouglasVinicius commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BillingAg] Check mandatory properties](https://trello.com/c/jzdzP2eq/982-billingag-check-mandatory-properties)

2022-08-18 18:59 UTC, ricardosantacattarina requested changes
Nice job! I suggested a lot of nitpicking :smile: let me know what you think
Regarding exceptions, I read only now in the card that `When a property is invalid, we should write an error message and abort the job with a System.exit(1).`, so maybe instead of exiting, we throw an exception, catch it and log before doing the exit call.

2022-08-18 18:59 UTC, ricardosantacattarina commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +        String normalizedPathTarget = normalizePath(sparkProperties.get(TARGET_BASE_PATH));
What about something like this?
`String normalizedPathSource = Optional.ofNullable(sparkProperties.get(SOURCE_BASE_PATH)).map(this::normalizePath).orElseThrow(new ExceptionName)` or `orElse(() -> System.exit(1))` if you prefer

2022-08-18 18:59 UTC, ricardosantacattarina commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +    }
you could refactor this to assert only 1 path per call

2022-08-18 18:59 UTC, ricardosantacattarina commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +                System.exit(1);
is there a reason for system.exit(1) instead of exceptions? I haven't played in this repository yet so I'm genuinely curious

2022-08-18 18:59 UTC, ricardosantacattarina commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +    public static boolean notIsADirectory(FileSystem fileSystem, Path folderPath) throws IOException {
```suggestion
    public static boolean IsNotADirectory(FileSystem fileSystem, Path folderPath) throws IOException {
```

2022-08-18 18:59 UTC, ricardosantacattarina commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +    public static boolean pathExist(FileSystem fileSystem, Path folderPath) throws IOException {
```suggestion
    public static boolean pathExists(FileSystem fileSystem, Path folderPath) throws IOException {
```

2022-08-18 18:59 UTC, ricardosantacattarina commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +    }
Is there a trim method in Java 
```suggestion
    private static String normalizePath(String path){
        return path.endsWith("/") ? StringUtils.chop(path) : path;
    }
```
I don't think I've ever used StringUtils but I saw it being used in one of Fabyan's PR, you could take a look into it to see if something like what I'm suggesting is possible. I only did a quick google search for chop and endsWith, maybe there's a `trim` method that already does exactly this :man_shrugging:

2022-08-18 18:59 UTC, ricardosantacattarina commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +    }
in case you're not familiar with ternary, it works like this: (condition) ? (value if condition true) : (value if condition false)

2022-08-18 18:59 UTC, ricardosantacattarina commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +    }
```suggestion
    public static boolean PathIsNotNull(String path){
        return !(path == null);
    }
```
something like this maybe? but it is so small I don't know if is worth to keep haha

2022-08-18 18:59 UTC, ricardosantacattarina commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +        validateEntriesPath(normalizedPathSource, normalizedPathTarget);
```suggestion
        validatePath(normalizedPathSource);
        validatePath(normalizedPathTarget);
```

2022-08-18 18:59 UTC, ricardosantacattarina commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +    private static Path getPathForFiles(URI fileUri) {
```suggestion
    private static Path getPathForFileURI(URI fileUri) {
```

2022-08-19 17:48 UTC, DouglasVinicius commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +        String normalizedPathTarget = normalizePath(sparkProperties.get(TARGET_BASE_PATH));
Thanks, here I changing the null verification to a more compact form.
commit: https://github.com/Leaf-Agriculture/billing-data-aggregation-job/pull/6/commits/c35585ec866ae475dac2134ad2c793d4c2ae0261

2022-08-19 18:23 UTC, DouglasVinicius commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +    }
Thanks, Ricardo!
Here I changed this validation to operate with only one parameter at a time: https://github.com/Leaf-Agriculture/billing-data-aggregation-job/pull/6/commits/b8b83cf53e1beefe551278d06913a9c3abe04c2e

2022-08-19 18:39 UTC, DouglasVinicius commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +                System.exit(1);
As Fabyan says in the daily, we don't know very well how it will behave with the exception (if the spark will end with exit 1).
I'm changing it on this commit https://github.com/Leaf-Agriculture/billing-data-aggregation-job/pull/6/commits/c96cd9175bc42dbee7bb5c013948cdc8e56ecbb0 for working with Exception instead, but if the behavior is not expected we can change to "try and catch" in the main, where the catch will call System.exit(1)

2022-08-19 18:42 UTC, DouglasVinicius commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +    public static boolean notIsADirectory(FileSystem fileSystem, Path folderPath) throws IOException {
Thanks, here I changed it: https://github.com/Leaf-Agriculture/billing-data-aggregation-job/pull/6/commits/5ff0816f8fd9783d00785035cf9ebabe020601e0

2022-08-19 18:46 UTC, DouglasVinicius commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +    }
Thanks, Ricardo! This method doesn't exist more because I implemented your first suggestion on this commit: https://github.com/Leaf-Agriculture/billing-data-aggregation-job/pull/6/commits/c35585ec866ae475dac2134ad2c793d4c2ae0261

2022-08-19 18:48 UTC, DouglasVinicius commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +        validateEntriesPath(normalizedPathSource, normalizedPathTarget);
Thanks, Ricardo!
Here I changed this validation to operate with only one parameter at a time: https://github.com/Leaf-Agriculture/billing-data-aggregation-job/commit/b8b83cf53e1beefe551278d06913a9c3abe04c2e
and here I changed the name of this method: https://github.com/Leaf-Agriculture/billing-data-aggregation-job/pull/6/commits/faf19ac465e54157f32ab88ed42b6298047a9074

2022-08-19 18:51 UTC, DouglasVinicius commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +    private static Path getPathForFiles(URI fileUri) {
Thanks, here I changed it: https://github.com/Leaf-Agriculture/billing-data-aggregation-job/pull/6/commits/c0e2ce111ae880de11471ced221f92497a443844

2022-08-19 18:52 UTC, DouglasVinicius commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +    public static boolean pathExist(FileSystem fileSystem, Path folderPath) throws IOException {
Thanks, here I changed it: https://github.com/Leaf-Agriculture/billing-data-aggregation-job/pull/6/commits/da9903e0a4026ab2655b06b98918237879aa2090

2022-08-19 19:16 UTC, DouglasVinicius commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +    }
Thanks, Ricardo! I searched in StringUtils and found the strip method that solves all things in one line, then here is the commit that implemented it: https://github.com/Leaf-Agriculture/billing-data-aggregation-job/pull/6/commits/4bb4f8a8928a3e5eef6c275df2209258a069cac1

2022-08-19 19:53 UTC, ricardosantacattarina commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +    }
nice, does this keep the slash if its in the beginning of the path? maybe we should use stripEnd :thinking:

2022-08-19 20:15 UTC, ricardosantacattarina approved these changes
Nice job! Still some nitpicking left

2022-08-19 20:15 UTC, ricardosantacattarina commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +    private static FileSystem getFileSystemForFiles(URI fileUri) throws IOException {
```suggestion
    private static FileSystem getFileSystemForFileURI(URI fileUri) throws IOException {
```
sorry nitpicking again

2022-08-22 21:50 UTC, DouglasVinicius commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +    }
Thanks Ricardo, I changed it on this commit: https://github.com/Leaf-Agriculture/billing-data-aggregation-job/pull/6/commits/ff524cba7f9e770d8e74999ec97e9d78bb033e72

2022-08-22 21:53 UTC, DouglasVinicius commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +            throw new InvalidPathException(String.format("Path to JobProperties don't exists, normalized path: %s", normalizedPath));
Thanks Ricardo, I changed it on this commit: https://github.com/Leaf-Agriculture/billing-data-aggregation-job/pull/6/commits/17a143be1a75a42bd0df49c3041efbed61424414 
and here: https://github.com/Leaf-Agriculture/billing-data-aggregation-job/pull/6/commits/79bd23f2c5264c7c56bfe72f2ba907277ee4c761

2022-08-22 21:53 UTC, DouglasVinicius commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +    private static FileSystem getFileSystemForFiles(URI fileUri) throws IOException {
Thanks Ricardo, I changed it on this commit: https://github.com/Leaf-Agriculture/billing-data-aggregation-job/pull/6/commits/17a143be1a75a42bd0df49c3041efbed61424414 
and here: https://github.com/Leaf-Agriculture/billing-data-aggregation-job/pull/6/commits/79bd23f2c5264c7c56bfe72f2ba907277ee4c761

2022-08-22 22:06 UTC, fabyan-alexander commented on src/main/java/com/leaf/billing/exceptions/InvalidPathException.java
> +    }
Are you using this constructor? If not, you can delete this one :sweat_smile:

2022-08-22 22:14 UTC, DouglasVinicius commented on src/main/java/com/leaf/billing/exceptions/InvalidPathException.java
> +    }
Yes, in the lines 33 and 34 of the file PropertyBuilder

2022-08-23 13:51 UTC, fabyan-alexander requested changes
Nice work!
There is just one point to review.

2022-08-23 13:51 UTC, fabyan-alexander commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +        String normalizedPathTarget = Optional.ofNullable(sparkProperties.get(TARGET_BASE_PATH)).map(PropertyBuilder::normalizePath).orElseThrow(InvalidPathException::new);
Do not throw an exception without including a message explaining what is happening.
We have some possibilities here and your message is not giving more details about the cause of that exception.

2022-08-23 18:36 UTC, DouglasVinicius commented on src/main/java/com/leaf/billing/utils/PropertyBuilder.java
> +        String normalizedPathTarget = Optional.ofNullable(sparkProperties.get(TARGET_BASE_PATH)).map(PropertyBuilder::normalizePath).orElseThrow(InvalidPathException::new);
Thanks for the explanation Fabyan! Here I changed it to implement your suggestion: https://github.com/Leaf-Agriculture/billing-data-aggregation-job/pull/6/commits/66c3f33d369de1e596d05af6b581f98be0bd81a8

2022-08-24 16:45 UTC, fabyan-alexander requested changes
The error message is still vague.

2022-08-24 16:45 UTC, fabyan-alexander commented on src/test/java/com/leaf/billing/PropertyParserTest.java
> +    void assertFalseWhenAtLeastOnePathIsNull(String sourcePath, String targetPath){
Is it okay to return a generic error instead of pointing exactly to which property is incorrect and why?

2022-08-24 19:31 UTC, DouglasVinicius commented on src/test/java/com/leaf/billing/PropertyParserTest.java
> +    void assertFalseWhenAtLeastOnePathIsNull(String sourcePath, String targetPath){
Thanks Fabyan, I changed it on this commit: https://github.com/Leaf-Agriculture/billing-data-aggregation-job/pull/6/commits/660374a0dd033991480ea4989e598539c7e062d3

2022-08-24 20:10 UTC, fabyan-alexander approved these changes
Nice work!
You can now merge it!

2022-08-25 13:59 UTC, merged